# .NET workflow with private github packages
name: .NET

env:
    # repository secret PACKAGES_TOKEN is required to access private packages
    NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_NOLOGO: true
    
on:
  push:
    branches: [ develop, master, feature/* ]
  pull_request:
    branches: [ develop, master ]

defaults:
  run:
    working-directory: src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    - name: Restore dependencies
      run: |
        dotnet restore Janda.Runtime.Watchers.sln
        # dotnet restore Janda.Runtime.Watchers.Console.sln
    - name: Build
      run: |
        dotnet build Janda.Runtime.Watchers.sln --no-restore
        # dotnet build Janda.Runtime.Watchers.Console.sln --no-restore
# there's a problem with running tests. Perhaps after moving to 5 this problem will be resolved.
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
